---
- name: Install PIP packages
  pip: name={{ item }}
  with_items:
    - virtualenv
    - fabric
    - virtualenvwrapper
    - pylint
    - ipython
    - flake8
    - pythonpy
    - termrule
    - speedtest-cli
